#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export PATH="$PATH:$HOME/scripts"
export PATH="$PATH:$HOME/scripts/wal"

wal -r

[ -n "$XTERM_VERSION" ] && transset-df --id "$WINDOWID" >/dev/null